#!/bin/bash
# MySQL Root Password Reset Guide for macOS
# This script provides instructions - you'll need to run commands manually with sudo

echo "======================================"
echo "MySQL Root Password Reset Guide"
echo "======================================"
echo ""
echo "Follow these steps to reset your MySQL root password:"
echo ""
echo "1. Stop MySQL server:"
echo "   sudo /usr/local/mysql/support-files/mysql.server stop"
echo ""
echo "2. Start MySQL in safe mode (skip grant tables):"
echo "   sudo /usr/local/mysql/bin/mysqld_safe --skip-grant-tables &"
echo "   (Wait 5-10 seconds for it to start)"
echo ""
echo "3. In a NEW terminal, connect to MySQL without password:"
echo "   /usr/local/mysql/bin/mysql -u root"
echo ""
echo "4. Once in MySQL prompt, run these commands:"
echo "   FLUSH PRIVILEGES;"
echo "   ALTER USER 'root'@'localhost' IDENTIFIED BY 'your_new_password';"
echo "   FLUSH PRIVILEGES;"
echo "   EXIT;"
echo ""
echo "5. Stop safe mode and restart MySQL:"
echo "   sudo killall mysqld"
echo "   sudo /usr/local/mysql/support-files/mysql.server start"
echo ""
echo "6. Test your new password:"
echo "   mysql -u root -p"
echo "   (Enter your new password when prompted)"
echo ""
echo "======================================"
echo ""
echo "Alternative: Use MySQL without password (not recommended for production)"
echo "You can also configure MySQL to allow root login without password:"
echo "   sudo /usr/local/mysql/bin/mysql_secure_installation"
echo ""
